version: "3.8"
services:
  redis-dlm-1:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"

  redis-dlm-2:
    image: redis:7.0.5-alpine
    ports:
      - "6380:6379"

  redis-dlm-3:
    image: redis:7.0.5-alpine
    ports:
      - "6381:6379"

  redis-dlm-4:
    image: redis:7.0.5-alpine
    ports:
      - "6382:6379"

  redis-dlm-5:
    image: redis:7.0.5-alpine
    ports:
      - "6383:6379"

networks:
  default:
    name: redis-dlm-shared
